version: "3.3"
services:
  qrm_server:
    image: finalil/qrm_server:0.0.2
    network_mode: "host"
    pid: "host"
    container_name: qrm_server
    depends_on:
      - redis_db
    volumes:
      - "/tmp/log:/tmp/log"

  mgmt_server:
    image: finalil/qrm_mgmt_server:0.0.2
    network_mode: "host"
    pid: "host"
    container_name: mgmt_server
    depends_on:
      - redis_db
    volumes:
      - "/tmp/log:/tmp/log"


