version: "3.9"
services:
  qrm_server:
    image: finalil/qrm_server
    network_mode: "host"
    pid: "host"
    container_name: qrm_server
  
  mgmt_server:
    image: finalil/qrm_mgmt_server
    network_mode: "host"
    pid: "host"
    container_name: mgmt_server

  redis_db:
    image: redis:6.2.6
    ports:
      - "6379:6379"
    pid: "host"
    container_name: redis_db
