name: build-mgmt-server

on:
  workflow_dispatch:
    inputs:
      version_type:
        type: choice
        description: Version type
        options:
        - patch
        - minor
        - major
        required: true

jobs:
  run_tests:
    uses: ./.github/workflows/test-server-and-client.yml

  coverage:
    uses: ./.github/workflows/coverage-report.yml

  docker:
    needs: [run_tests, coverage]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: prepare env
        run: |
          make -f Makefile_mgmtserver install_py_req

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Stamp with vmn
        id: vmn_version
        uses: progovoy/vmn-action@vmna_0.1.78
        with:
          release-mode: ${{ github.event.inputs.version_type }}
          app-name: qrm_server
        env:
          GITHUB_TOKEN: ${{ github.TOKEN }}

      - name: show version vmn
        run: |
          vmn show qrm_mgmt_server --verbose > ./qrm_server/mgmt_ver.yaml
          echo "cat ./qrm_server/mgmt_ver.yaml"
          cat ./qrm_server/mgmt_ver.yaml

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          file: DockerfileMgmtServer
          push: true
          tags: finalil/qrm_mgmt_server:${{ steps.vmn_version.outputs.verstr }},finalil/qrm_mgmt_server:latest
