name: build-mgmt-server

on:
  workflow_dispatch:
    inputs:
      version_type:
        type: choice
        description: Version type
        options:
        - patch
        - minor
        - major
        - debug
        required: true

jobs:
  run_tests:
    uses: ./.github/workflows/test-server-and-client.yml

  coverage:
    uses: ./.github/workflows/coverage-report.yml

  docker:
    needs: [run_tests, coverage]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: prepare env
        run: |
          make -f Makefile_mgmtserver install_py_req

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Stamp with vmn
        run: |
          echo "debug print ${{ github.event.inputs.version_type }}"
          if [ ${{ github.event.inputs.version_type != 'debug' }}  ]
          then
            make ${{ github.event.inputs.version_type
#            vmn stamp -r ${{ github.event.inputs.version_type }} qrm_mgmt_server
#            vmn show qrm_mgmt_server --verbose > ./qrm_server/mgmt_ver.yaml
#            echo "cat ./qrm_server/mgmt_ver.yaml"
#            cat ./qrm_server/mgmt_ver.yaml
          fi

      - name: "Set version from Commit"
        id: get_version
        run: |
          echo "version=$(vmn show qrm_mgmt_server --ignore-dirty)" >> $GITHUB_ENV

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          file: DockerfileMgmtServer
          push: true
          tags: finalil/qrm_mgmt_server:${{ env.version }},finalil/qrm_mgmt_server:latest
