# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: coverage QRM server and client

on:
  #push:
  #  branches: [ main, code_cov ]
  #pull_request:
  #branches: [ main ]
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
          python-version: [3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        sudo apt install -y redis-server
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f qrm_client/requirements.txt ]; then pip install -r qrm_client/requirements.txt; fi
        if [ -f qrm_server/requirements.txt ]; then pip install -r qrm_server/requirements.txt; fi
        if [ -f test_requirements.txt ]; then pip install -r test_requirements.txt; fi
        if [ -f env_requirements.txt ]; then pip install -r env_requirements.txt; fi
        sudo service redis-server stop
    - name: Test with pytest and coverage
      run: |
        python -m coverage run -m pytest --reruns 3 tests/
        python -m coverage xml
    - name: Build covereage report
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./coverage.xml
